spring.application.name=auth-service

#Configuration BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}

#Configuration SS
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION}
